### ISSUE TITLE
Installation instructions needs update: openldap24-libs-devel

### ISSUE THREAD

**Issue by msunardi** [PSU-OIT-ARC/traq#26]
In the installation instructions, it said to first install openldap by:

`yum install openldap24-libs-devel`

yum couldn't find that package. Maybe the package name is not correct (anymore)? What's currently available on the centos65 box are `openldap.x86_64`, `openldap-devel.x86_64`, etc.

**Comment by mdj2** [comment]
Now the README excludes that information. We will operate under the assumption that developers on traq will base their VMs off of https://github.com/PSU-OIT-ARC/vagrant-manifest which has the proper LDAP stuff installed.
